### ISSUE TITLE
Unable to class load the plugin net.blay09.mods.defaultkeys.coremod.DefaultOptionsLoadingPlugin

### ISSUE THREAD

**Issue by leezallen** [blay09/DefaultKeyConfig#12]
The following error is appearing in my log file.... It's weird because the mod loads and I can save default configs, they are just never being applied!

[16:06:30] [main/DEBUG] [FML/]: Instantiating coremod class DefaultOptionsLoadingPlugin
[16:06:30] [main/ERROR] [FML/]: Coremod DefaultOptionsLoadingPlugin: Unable to class load the plugin net.blay09.mods.defaultkeys.coremod.DefaultOptionsLoadingPlugin
java.lang.ClassNotFoundException: net.blay09.mods.defaultkeys.coremod.DefaultOptionsLoadingPlugin
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_25]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
    at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
    at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:485) [forge-1.8-11.14.4.1577.jar:?]
    at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:409) [forge-1.8-11.14.4.1577.jar:?]
    at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:241) [forge-1.8-11.14.4.1577.jar:?]
    at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:95) [forge-1.8-11.14.4.1577.jar:?]
    at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:72) [forge-1.8-11.14.4.1577.jar:?]
    at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.8-11.14.4.1577.jar:?]
    at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:119) [forge-1.8-11.14.4.1577.jar:?]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by leezallen** [comment]
Should have mentioned that this is the 1.8 version!

**Comment by BlayTheNinth** [comment]
What version are you running on? This should have been fixed on version 3.0.7+.

**Comment by leezallen** [comment]
Its version 2.0.14 for version 1.8.... I cant move the modpack up to version 1.8.9 yet, still waiting for a couple of mods!

**Comment by leezallen** [comment]
Just to clarify. Does that mean that there is no working version for 1.8 or is there a conflict that I can look at?
